# Generated by Django 2.1 on 2018-08-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='nodes',
            new_name='notes',
        ),
    ]
